// auth-autonome.selfcheck.ts - session acheteur, anti-rejeu, limites atomiques et challenge obligatoire.
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { authAutonome, type AuthAutonomeEnv } from "./auth-autonome.ts";
const db = new DatabaseSync(":memory:");
db.exec("CREATE TABLE aloha_auth_limits (key TEXT PRIMARY KEY, window INTEGER NOT NULL, attempts INTEGER NOT NULL); CREATE TABLE aloha_auth_used (fingerprint TEXT PRIMARY KEY, expires INTEGER NOT NULL);");
const env: AuthAutonomeEnv = { ALOHA_AUTH_SECRET: "test-only-secret-not-a-real-credential", ALOHA_ADMIN_EMAILS: "admin@example.test", ALOHA_TURNSTILE_SITE_KEY: "site-test", ALOHA_TURNSTILE_SECRET_KEY: "challenge-test", ALOHA_MAIL_KEY: "mail-test", ALOHA_MAIL_FROM: "admin@example.test", ALOHA_AUTH_DB: { prepare(sql) { let params: unknown[] = []; return { bind(...values) { params = values; return this; }, async first<T>() { return (db.prepare(sql).get(...params as (string | number)[]) ?? null) as T | null; }, async run() { return db.prepare(sql).run(...params as (string | number)[]); } }; } } };
let code = "", challengeHost = "buyer.example.test", mailCalls = 0;
const transport = (async (url: RequestInfo | URL, init?: RequestInit) => {
  if (String(url).includes("siteverify")) return Response.json({ success: true, hostname: challengeHost });
  assert.equal(String(url), "https://api.resend.com/emails");
  const mail = JSON.parse(String(init?.body)); assert.deepEqual(mail.to, ["admin@example.test"]); code = mail.text.match(/\d{6}/)[0]; mailCalls++;
  return Response.json({ id: "test" });
}) as typeof fetch;
const origin = "https://buyer.example.test";
const auth = authAutonome(env, origin, transport)!;
const post = (path: string, body: unknown, from = origin) => auth.fetch(new Request(origin + path, { method: "POST", headers: { Origin: from, "Content-Type": "application/json" }, body: JSON.stringify(body) }));
assert.equal(authAutonome({ ...env, ALOHA_AUTH_SECRET: "short" }, origin), null);
assert.equal((await post("/api/auth/request", { email: "admin@example.test" }, "https://evil.example")).status, 403);
assert.equal((await post("/api/auth/request", { email: "admin@example.test" })).status, 400);
challengeHost = "evil.example";
assert.equal((await post("/api/auth/request", { email: "admin@example.test", turnstile: "token" })).status, 400);
assert.equal(mailCalls, 0); challengeHost = "buyer.example.test";
assert.equal((await post("/api/auth/request", { email: "unknown@example.test", turnstile: "token" })).status, 200);
assert.equal(mailCalls, 0);
assert.equal((await post("/api/auth/request", { email: "admin@example.test", turnstile: "token" })).status, 200);
assert.equal(mailCalls, 1);
assert.equal((await post("/api/auth/verify", { email: "admin@example.test", code: "invalid" })).status, 401);
const signed = await post("/api/auth/verify", { email: "admin@example.test", code }); assert.equal(signed.status, 200);
const cookie = signed.headers.get("set-cookie")!; assert.match(cookie, /HttpOnly; Secure; SameSite=Lax/);
const me = () => auth.fetch(new Request(origin + "/api/auth/me", { headers: { Cookie: cookie } }));
assert.equal((await (await me()).json() as { authenticated: boolean }).authenticated, true);
assert.equal((await post("/api/auth/verify", { email: "admin@example.test", code })).status, 401);
env.ALOHA_ADMIN_EMAILS = "other@example.test";
assert.equal((await (await me()).json() as { authenticated: boolean }).authenticated, false);
env.ALOHA_ADMIN_EMAILS = "admin@example.test";
for (let i = 0; i < 8; i++) await post("/api/auth/verify", { email: "admin@example.test", code: "invalid" });
assert.equal((await post("/api/auth/verify", { email: "admin@example.test", code })).status, 429);
db.close();
console.log("Connexion autonome : session, challenge, destinataire, anti-rejeu, revocation et limites verifies.");
